backbone: se_resnext50_32x4d
exp_name: roi-batch-large-min-epoch-non-trivial
description: set min epoch = 70, do not use early stopping
# data_folder: /data/lxd/datasets/2022-03-02-Eggs
data_folder: /data/lxd/datasets/2022-03-17-Egg-Masks/
training_set: train_4_3.csv
test_set : test_4_1.csv
num_classes: 8
lr: 0.001
# training 
train_transforms: non-trivial             
train_batch_size: 48
fold_i: 0
val_batch_size: 96
anchor_batch_size: 6
training_mode: ddp
num_workers: 8
image_size: [600, 600]
seed: 2022
min_epochs: 70
max_epochs: 70
gpus: [0,1]
precision: 16
gradient_clip_val: 0
soft_labels_filename: ""
log_dir: logs_submit
sample_num: 6
debug: false
# normalization:
#   mean: [0.4914, 0.4822, 0.4465]
#   std: [0.247, 0.243, 0.261]
norm: 
  mean: [
    0.4755111336708069,
    0.15864244103431702,
    0.09940344840288162
  ]
  std: [
    0.33696553111076355,
    0.295562744140625,
    0.2568116784095764
  ]
resume_from_checkpoint: 
checkpoints: 
 - logs_submit/20220319-0212/checkpoints/fold=0-epoch=37-val_loss=0.2775-val_roc_auc=0.9872.ckpt